### ISSUE TITLE
Scaramuzza not finished

### ISSUE THREAD

**Issue by ouyangandy** [hengli/camodocal#103]
Scaramuzza not implemented，so，how to get Scaramuzza Intrinsics...

**Comment by ouyangandy** [comment]
fixed it

**Comment by wolf943134497** [comment]
> fixed it

Hi @ouyangandy  Has the Scaramuzza  camera model been implemented?  I found that this model is still not implemented in the source code. 
many thanks!
